# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(752, 564)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        #self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        #self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        #self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        #self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lstreaders = QtWidgets.QListWidget(self.centralWidget)
        self.lstreaders.setObjectName("lstreaders")
        self.verticalLayout.addWidget(self.lstreaders)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        #self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        #self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbpreview = QtWidgets.QPushButton(self.centralWidget)
        self.pbpreview.setObjectName("pbpreview")
        self.horizontalLayout.addWidget(self.pbpreview)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pbreaderconfig = QtWidgets.QPushButton(self.centralWidget)
        self.pbreaderconfig.setObjectName("pbreaderconfig")
        self.horizontalLayout.addWidget(self.pbreaderconfig)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        #self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        #self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lstprocess = QtWidgets.QListWidget(self.centralWidget)
        self.lstprocess.setObjectName("lstprocess")
        self.verticalLayout_4.addWidget(self.lstprocess)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        #self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        #self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pbprocessconfig = QtWidgets.QPushButton(self.centralWidget)
        self.pbprocessconfig.setObjectName("pbprocessconfig")
        self.horizontalLayout_2.addWidget(self.pbprocessconfig)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        #self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        #self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lstwriters = QtWidgets.QListWidget(self.centralWidget)
        self.lstwriters.setObjectName("lstwriters")
        self.verticalLayout_5.addWidget(self.lstwriters)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        #self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        #self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pbwriterconfig = QtWidgets.QPushButton(self.centralWidget)
        self.pbwriterconfig.setObjectName("pbwriterconfig")
        self.horizontalLayout_3.addWidget(self.pbwriterconfig)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab1)
        #self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        #self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.txtlog = QtWidgets.QTextEdit(self.tab1)
        self.txtlog.setObjectName("txtlog")
        self.verticalLayout_2.addWidget(self.txtlog)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab2)
        #self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        #self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tblwidget = QtWidgets.QTableWidget(self.tab2)
        self.tblwidget.setObjectName("tblwidget")
        self.tblwidget.setColumnCount(0)
        self.tblwidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tblwidget)
        self.tabWidget.addTab(self.tab2, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.actionRefresh = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/refresh.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionRun = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/run.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon1)
        self.actionRun.setObjectName("actionRun")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName("actionExit")
        self.mainToolBar.addAction(self.actionRefresh)
        self.mainToolBar.addAction(self.actionRun)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Format Converter"))
        self.pbpreview.setText(_translate("MainWindow", "Preview"))
        self.pbreaderconfig.setText(_translate("MainWindow", "config"))
        self.pbprocessconfig.setText(_translate("MainWindow", "config"))
        self.pbwriterconfig.setText(_translate("MainWindow", "config"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Task Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Task Progress"))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
        self.actionExit.setText(_translate("MainWindow", "exit"))

#import icons_rc